#!/usr/bin/env bash
# SOPS bootstrap for test-vm.
# Generates an age keypair for sops-nix, wires up .sops.yaml, and encrypts
# secrets.yaml. The age private key is stored as GitHub secret SOPS_AGE_KEY
# and planted at /var/lib/sops-nix/age.key via nixos-anywhere --extra-files.
#
# Prerequisites (macOS without Nix):
#   brew install sops age

set -euo pipefail

# ── Preflight: required tools ────────────────────────────────────────────────
MISSING=()
for cmd in sops age-keygen; do
  command -v "$cmd" &>/dev/null || MISSING+=("$cmd")
done
if (( ${#MISSING[@]} > 0 )); then
  echo "ERROR: Missing required tools: ${MISSING[*]}"
  echo "  macOS (no Nix): brew install sops age"
  echo "  With Nix:       nix develop .#   (from repo root)"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_DIR="$(dirname "$SCRIPT_DIR")"
SECRETS_DIR="$TEST_DIR/secrets"
AGE_KEY_FILE="$SECRETS_DIR/extra-files/var/lib/sops-nix/age.key"
SOPS_YAML="$TEST_DIR/.sops.yaml"

echo "=== SOPS bootstrap for test-vm ==="
echo ""

# ── Step 1: Generate sops-nix age keypair ───────────────────────────────────
if [[ -f "$AGE_KEY_FILE" ]]; then
  echo "→ Age key already exists, skipping generation."
else
  echo "→ Generating age keypair for sops-nix..."
  mkdir -p "$(dirname "$AGE_KEY_FILE")"
  age-keygen -o "$AGE_KEY_FILE" 2>/dev/null
  chmod 600 "$AGE_KEY_FILE"
fi

AGE_PUB=$(age-keygen -y "$AGE_KEY_FILE")
echo "→ sops-nix age public key: $AGE_PUB"

# ── Step 2: Get operator age public key ─────────────────────────────────────
DEFAULT_AGE_FILE="$HOME/.config/sops/age/keys.txt"
if [[ -f "$DEFAULT_AGE_FILE" ]]; then
  OPERATOR_AGE_KEY=$(age-keygen -y "$DEFAULT_AGE_FILE")
  echo "→ Operator key derived from $DEFAULT_AGE_FILE: $OPERATOR_AGE_KEY"
else
  echo ""
  echo "No age keyfile found at $DEFAULT_AGE_FILE."
  echo "Generate one with: age-keygen -o ~/.config/sops/age/keys.txt"
  echo ""
  read -rp "Operator age PUBLIC key (age1...): " OPERATOR_AGE_KEY
fi

# ── Step 3: Write .sops.yaml ─────────────────────────────────────────────────
cat > "$SOPS_YAML" << EOF
---
# Generated by scripts/bootstrap-sops.sh — do not edit by hand.

creation_rules:
  - path_regex: secrets/.*\\.yaml\$
    key_groups:
      - age:
          # sops-nix age key (planted at /var/lib/sops-nix/age.key via --extra-files)
          - ${AGE_PUB}
          # Operator key
          - ${OPERATOR_AGE_KEY}
EOF
echo "→ Written $SOPS_YAML"

# ── Step 4: Create and encrypt secrets.yaml ──────────────────────────────────
if [[ -f "$SECRETS_DIR/secrets.yaml" ]]; then
  echo "→ secrets.yaml already exists. Delete it and re-run to recreate."
else
  TAILSCALE_KEY="${TAILSCALE_AUTH_KEY:-}"
  if [[ -z "$TAILSCALE_KEY" ]]; then
    echo ""
    read -rsp "Tailscale auth key (will not echo): " TAILSCALE_KEY
    echo ""
  fi

  echo "tailscale-auth-key: ${TAILSCALE_KEY}" > "$SECRETS_DIR/secrets.yaml"
  (cd "$TEST_DIR" && sops -e -i secrets/secrets.yaml)
  echo "→ Encrypted secrets written to $SECRETS_DIR/secrets.yaml"
fi

echo ""
echo "=== Bootstrap complete ==="
echo ""
echo "GitHub secret to set:"
echo "  SOPS_AGE_KEY  →  contents of: $AGE_KEY_FILE"
echo "  (a single line starting with AGE-SECRET-KEY-1...)"
echo ""
echo "You can copy it with:"
echo "  cat '$AGE_KEY_FILE' | pbcopy"
echo ""
echo "Next: run  scripts/deploy.sh   (or push and trigger the GitHub Actions workflow)"
