#!/usr/bin/env bash
# SOPS bootstrap for test-vm.
# Generates a pre-shared host SSH keypair, wires up .sops.yaml, and encrypts
# secrets.yaml — so nixos-anywhere can plant the key and sops-nix can decrypt
# on first boot without the chicken-and-egg problem.
#
# Prerequisites (macOS without Nix):
#   brew install sops age
#   go install github.com/Mic92/ssh-to-age/cmd/ssh-to-age@latest

set -euo pipefail

# ── Preflight: required tools ────────────────────────────────────────────────
MISSING=()
for cmd in sops age-keygen ssh-keygen ssh-to-age; do
  command -v "$cmd" &>/dev/null || MISSING+=("$cmd")
done
if (( ${#MISSING[@]} > 0 )); then
  echo "ERROR: Missing required tools: ${MISSING[*]}"
  echo "  macOS (no Nix): brew install sops age"
  echo "                  go install github.com/Mic92/ssh-to-age/cmd/ssh-to-age@latest"
  echo "  With Nix:       nix develop .#   (from repo root)"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_DIR="$(dirname "$SCRIPT_DIR")"
SECRETS_DIR="$TEST_DIR/secrets"
KEY_DIR="$SECRETS_DIR/extra-files/etc/ssh"
SOPS_YAML="$TEST_DIR/.sops.yaml"

echo "=== SOPS bootstrap for test-vm ==="
echo ""

# ── Step 1: Generate host SSH keypair ────────────────────────────────────────
if [[ -f "$KEY_DIR/ssh_host_ed25519_key" ]]; then
  echo "→ Host keypair already exists, skipping generation."
else
  echo "→ Generating host SSH keypair..."
  mkdir -p "$KEY_DIR"
  ssh-keygen -t ed25519 -f "$KEY_DIR/ssh_host_ed25519_key" -N "" -C "test-vm host key"
  chmod 600 "$KEY_DIR/ssh_host_ed25519_key"
  chmod 644 "$KEY_DIR/ssh_host_ed25519_key.pub"
fi

HOST_AGE_KEY=$(ssh-to-age -i "$KEY_DIR/ssh_host_ed25519_key.pub")
echo "→ Host age key: $HOST_AGE_KEY"

# ── Step 2: Get operator age public key ─────────────────────────────────────
DEFAULT_AGE_FILE="$HOME/.config/sops/age/keys.txt"
if [[ -f "$DEFAULT_AGE_FILE" ]]; then
  OPERATOR_AGE_KEY=$(age-keygen -y "$DEFAULT_AGE_FILE")
  echo "→ Operator key derived from $DEFAULT_AGE_FILE: $OPERATOR_AGE_KEY"
else
  echo ""
  echo "No age keyfile found at $DEFAULT_AGE_FILE."
  echo "Generate one with: age-keygen -o ~/.config/sops/age/keys.txt"
  echo "Or paste an existing public key below."
  echo ""
  read -rp "Operator age PUBLIC key (age1...): " OPERATOR_AGE_KEY
fi

# ── Step 3: Write .sops.yaml ─────────────────────────────────────────────────
cat > "$SOPS_YAML" << EOF
---
# Generated by scripts/bootstrap-sops.sh — do not edit by hand.

creation_rules:
  - path_regex: secrets/.*\\.yaml\$
    key_groups:
      - age:
          # test-vm host key (pre-generated; planted via nixos-anywhere --extra-files)
          - ${HOST_AGE_KEY}
          # Operator key
          - ${OPERATOR_AGE_KEY}
EOF
echo "→ Written $SOPS_YAML"

# ── Step 4: Create and encrypt secrets.yaml ──────────────────────────────────
if [[ -f "$SECRETS_DIR/secrets.yaml" ]]; then
  echo "→ secrets.yaml already exists. Delete it and re-run to recreate."
else
  TAILSCALE_KEY="${TAILSCALE_AUTH_KEY:-}"
  if [[ -z "$TAILSCALE_KEY" ]]; then
    echo ""
    read -rsp "Tailscale auth key (will not echo): " TAILSCALE_KEY
    echo ""
  fi

  # Write plaintext then encrypt in-place from the test/ dir so .sops.yaml is found
  echo "tailscale-auth-key: ${TAILSCALE_KEY}" > "$SECRETS_DIR/secrets.yaml"
  (cd "$TEST_DIR" && sops -e -i secrets/secrets.yaml)
  echo "→ Encrypted secrets written to $SECRETS_DIR/secrets.yaml"
fi

echo ""
echo "=== Bootstrap complete ==="
echo ""
echo "Host key fingerprint (will appear on first SSH connect):"
ssh-keygen -lf "$KEY_DIR/ssh_host_ed25519_key.pub"
echo ""
echo "Next: run  scripts/deploy.sh"
